version: '3.8'

services:
  express_cookbook_front:
    build:
      context: ${PWD}/front
      dockerfile: Dockerfile.dev
    container_name: cookbook-front
    profiles: ["front", "all"]
    ports:
      - "4200:4200"
    volumes:
      - ${PWD}/front/:/front
  express_cookbook_back:
    build:
      context: ${PWD}/back
      dockerfile: Dockerfile.dev
    container_name: cookbook-back
    profiles: ["back", "all"]
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/back/:/back
  express_cookbook_db:
    image: postgres
    restart: always
    build:
      context: ${PWD}/db
      dockerfile: Dockerfile.dev
    container_name: cookbook-postgres
    profiles: ["db"]
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/back/:/back
