FROM node:18.16.1-alpine3.18

RUN npm config set strict-ssl false
RUN npm install -g @angular/cli

WORKDIR /front

COPY . .

RUN npm install

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "500"]
