# Stage 1 : Build Angular codebase
FROM node:18.16.1-alpine3.18 as build

WORKDIR /usr/local/app

COPY ./ /usr/local/app/

RUN npm install

RUN npm run build

# Stage 2 : Serve app
FROM nginx:latest

# front is name of the angular app
COPY --from=build /usr/local/app/dist/front /usr/share/nginx/html

EXPOSE 80

